version: "3"  
services:
  api:
    container_name: weather_api
    environment:
      DATABASE_PUBLIC_URL: "db"
      TZ: "Asia/Singapore"
    build: .
    volumes:
      - volume:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    container_name: weather_db
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd#"
      MSSQL_PID: "Developer"
      TZ: "Asia/Singapore"
    ports:
      - "1433:1433"
    volumes:
      - volume:/var/opt/mssql/data
volumes:
  volume: